### ISSUE TITLE
expect and test scripts additional features

### ISSUE THREAD

**Issue by VojislavM** [Ovyl/tabouli#6]
Could also add `expect`  functionality, where the script checks back if it received a valid response.
IMO, support for "test scripts" would provide a good basis for automated on-device tests that could be performed by the CI server.

Best, 
Voja

**Comment by nicksinas** [comment]
@VojislavM I like it. We were thinking something like this as the test file format, where `expect` is optional:
```
commands:
  - cmd: comm_test
    expect: '123'
  - cmd: ble
  - cmd: nfc
```  
  
Thoughts?
